<h1  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy
</h1>

In [1]:
import numpy

In [ ]:
# matrice vide
numpy.empty([3, 2]) # 3-lignes , 2-cols

In [ ]:
# matrice nulle
numpy.zeros(4)

In [ ]:
numpy.zeros([3,6])

In [ ]:
numpy.ones([3,3])

In [ ]:
[1]*4

In [ ]:
[0]*5

In [ ]:
# création d'un vecteur
v=numpy.array([2,1,5])
v

In [ ]:
v[0]

In [ ]:
v[1]

In [ ]:
# dim de v
v.shape

In [ ]:
v2=numpy.array([[1,5,6],[0,14,17]])
v2

In [ ]:
# dim de v2
v2.shape

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; ">
v2[i,j] :  i-1 ème ligne, j-1 ème col 
</h3>

In [ ]:
v2[1,1] # 2ème ligne, 2ème col

In [ ]:
v2[0,:] # 2ème ligne

In [ ]:
# matrice aléatoire à 3-lignes, 5-colonnes dont les élément sont dans l'ensemble {-5,..10}
v3=numpy.random.randint(-5,11,size=[3,5])
v3

In [ ]:
v3[:,3] # 4ème col

In [ ]:
# 
XX=numpy.random.randint(-7,11,size=15)
print(XX)
print(" éléments 0--7 avec incrément 2 \n")
print(XX[:7:2])  ## éléments 0--7 avec incrément 2

XX[::-1]
print("inverser l'ordre \n")
print(XX[::-1])

In [ ]:
# création de matrices

M = numpy.array([["({:},{:})".format(1+nb_col,1+nb_ligne) for nb_col in range(4)] for nb_ligne in range(6)]) 
M

In [ ]:
M.shape

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Transposé d'une matrice </h2>

In [ ]:
N=numpy.random.randint(-5,10,size=[2,3])
print("N=",N)
# transposé de N
print("\n")
print("# transposé : \n")
N.T

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Multipication
</h2>

In [ ]:
v4=numpy.random.randint(-5,11,size=[2,5])
v5=numpy.random.randint(-7,8,size=[4,2])

print('v4=',v4)
print('v5=',v5)

# produit : v5xv2 : (4,2)x(2,5) --> matrice : (4,5)
P=numpy.matmul(v5, v4)
print("Produit v5*v4= %s" %P)

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; ">
Produit scalaire
</h2>

In [ ]:
v6=numpy.random.randint(-2,2,size=5)
v6

In [ ]:
v7=numpy.random.randint(0,9,size=5)
v7

In [ ]:
numpy.dot(v6,v7)

In [ ]:
numpy.dot(v7,v6)

In [ ]:
#
M1=numpy.random.randint(-11,13,size=12)
print(M1)
M1.reshape((3,4)) # 3-ligne, 4-col

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Opérations sur les lignes et les colonnes d'une matrice
</h2>

In [ ]:
import numpy
M2=numpy.random.randint(-11,13,size=[3,7])
M2

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
somme des colonnes
</h3>

In [ ]:
numpy.sum(M2, axis=0) # somme des cols

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
somme des lignes
</h3>

In [ ]:
numpy.sum(M2, axis=1) # somme des lignes

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
max des colonnes
</h3>

In [ ]:
numpy.max(M2, axis=0) # max des cols

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
max des lignes
</h3>

In [ ]:
numpy.max(M2, axis=1) # max des lignes

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
min des colonnes
</h3>

In [ ]:
numpy.min(M2, axis=0) # min des cols

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
min des lignes
</h3>

In [ ]:
numpy.min(M2, axis=1) # min des lignes

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
moyenne empirique des colonnes
</h3>

In [ ]:
numpy.mean(M2, axis=0) # moyenne des cols

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
moyenne empirique des lignes
</h3>

In [ ]:
numpy.mean(M2, axis=1) # moyenne des lignes

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
variancee empirique des colonnes
</h3>

In [ ]:
numpy.var(M2, axis=0) # variance des cols

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
variance empirique des lignes
</h3>

In [ ]:
numpy.var(M2, axis=1) # variance des lignes

In [ ]:
MM=[5,8,9]
for x in MM:
    print(x)

In [ ]:
import numpy
NN=[5,7,4]
X=[]
for n in NN:
    X.append(numpy.random.randint(-4,4,n))

print(X)

print('***'*30)

# moyenne de chaque composant
M=[numpy.mean(X[i]) for i in range(len(X))]

for i in range(len(X)):
    print("X=%s , moyenne de X = %.4f \n"%(X[i],M[i]))


<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Indices
</h2>

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy.where
</h3>

In [ ]:
import numpy

A=numpy.random.randint(-11,5,13)
print('A=',A)
print("\n")
indice_positis= A>=0 


print('indice A>=0 :',indice_positis)
B=A[indice_positis]
print(B)

#where
print(" numpy.where")
X = numpy.arange(-2,11,1)
print("X=",X)
I=numpy.where( X > 5 )
print("I=numpy.where( X > 5 )=%s"%I)
print([X[j] for j in I][0])

print(" numpy.take ")

B = numpy.random.randint(-1,29,13)
indices = [0, 3, 7,10]
BB=numpy.take(B, indices)
print(B)
print("indices=%s"%indices)
print(BB)

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy.select
</h3>

In [ ]:
# numpy.select
C = numpy.random.randint(-7,19,15)
conditions = [C<2, C>5]
Vecteur = [C, C**2]
CC=numpy.select(conditions, Vecteur)
print("------------------------------")
print("numpy.select")
print("------------------------------")
print("C=",C)
print("------------Vecteur = [C, C**2] ------------------\n")
print(Vecteur)
print("------------------------------\n")
print(CC)


<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy.all  &  numpy.any
</h3>

In [ ]:
import numpy
#numpy.all
D=numpy.random.randint(-20,29,14)
print("D=%s"%D)
print("tous les éléments de D sont > 21 : numpy.all(D>21) : %s"%numpy.all(D>21))

#numpy.any
print("il y a des éléments de D qui sont < 21 : numpy.any(D<21) : %s"%numpy.any(D<21))

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy.isfinite
</h3>

In [ ]:
#numpy.isfinite
import numpy

C = numpy.random.randint(-7,19,8)
print("C=",C)
print(" on ajoute des éléments à C")
C=numpy.append(C,numpy.nan)
C=numpy.append(C,120)
print("nouveau C=",C)

print("\n ")
print("#numpy.isfinite : séléctionner des éléments qui sont finis")
C[numpy.isfinite(C)]

<h3  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
numpy.unique : occurrences d'une liste
</h3>

In [ ]:
# numpy.unique

H = numpy.random.randint(-5,10,23)
print("H=",H)
print("***"*31)

print("numpy.unique(H) : %s"%numpy.unique(H))

print("***"*31)
occurrence, frequence = numpy.unique(H, return_counts=True)

print("occurrence=",occurrence)

print("frequence=",frequence)

print("***"*31)

# création de dictionnaire

Dic_compte={}
for i in range(len(occurrence)):
    Dic_compte[occurrence[i]]=frequence[i]
    
Dic_compte
    

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Déterminant
</h2>

In [ ]:
M3=numpy.random.randint(-7,2,size=[4,4])
print("M3=",M3)

print("***"*31)
D=numpy.linalg.det(M3)
print("déterminant=%s"%D)

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Matrice inverse
</h2>

In [3]:
M4=numpy.random.randint(-7,2,size=[4,4])
print("M4=",M4)

print("***"*31)
numpy.linalg.inv(M4)

M4= [[-7  0  0  1]
 [-2 -1 -3 -3]
 [ 0  1  1 -3]
 [-2 -6  1 -2]]
*********************************************************************************************


array([[-0.13851351, -0.01182432, -0.03209459, -0.00337838],
       [ 0.04391892, -0.00844595,  0.11993243, -0.14527027],
       [ 0.0472973 , -0.23986486,  0.20608108,  0.07432432],
       [ 0.03040541, -0.08277027, -0.22466216, -0.02364865]])

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Puissance d'une matrice
</h2>

In [4]:
M5=numpy.random.randint(-7,3,size=[2,2])
print("M5=",M5)

print("***"*31)
print("M5^3=",numpy.linalg.matrix_power(M5, 3))

M5= [[ 2 -5]
 [-3 -1]]
*********************************************************************************************
M5^3= [[ 53 -90]
 [-54  -1]]


<h1  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; "> 
Systèmes Linéaires d'équations : AX=B
</h1>

<h3  style="background-color:  #b3b6b7; color:blue;padding:25px;border-radius: 25px; "> 
Première méthode
</h3>

In [5]:
import numpy
A = numpy.random.randint(-7,2,size=[3,3])
B = numpy.random.randint(5,13,size=[3,1])
X = numpy.linalg.solve(A, B)

print("***"*31)
print("A=%s \n B=%s\n"%(A,B))

print('-----------------solution  ---------------\n')
print("x=%s , y=%s , z=%s"%(X[0][0],X[1][0],X[2][0]))
###
print('-----------------vérification  ---------------\n')
print("AX=",numpy.dot(A , X))

*********************************************************************************************
A=[[ 0 -2 -3]
 [-3  1 -5]
 [-7  1 -3]] 
 B=[[11]
 [11]
 [ 7]]

-----------------solution  ---------------

x=-0.21875 , y=-1.84375 , z=-2.4375
-----------------vérification  ---------------

AX= [[11.]
 [11.]
 [ 7.]]


<h3  style="background-color:  #b3b6b7; color:blue;padding:25px;border-radius: 25px; "> 
Deuxième méthode
</h3>

In [6]:
import numpy

A = numpy.matrix([[-4 ,-6 ,-1],[-1 ,-4 ,-1],[-5,  1, -4]])
B = numpy.matrix([[11],[9],[11]])

print("***"*31)
print(" Matrice A=%s"%A)
print(" Vecteur B=%s"%B)
print("***"*31)
print("# utilisant matrice inverse de A")
X = A**(-1)*B
print("solution  : %s \n"%X)
print("vérification \n")

A*X


*********************************************************************************************
 Matrice A=[[-4 -6 -1]
 [-1 -4 -1]
 [-5  1 -4]]
 Vecteur B=[[11]
 [ 9]
 [11]]
*********************************************************************************************
# utilisant matrice inverse de A
solution  : [[ 0.30188679]
 [-1.45283019]
 [-3.49056604]] 

vérification 



matrix([[11.],
        [ 9.],
        [11.]])

<h2  style="background-color: #d5dbdb; color:blue;padding:25px;border-radius: 25px; ">  
concaténation
</h2>

In [7]:
# joint A et B
A = numpy.array([1, 2, 3])
B = numpy.array([-2, -3, 0])

numpy.vstack((A,B))

array([[ 1,  2,  3],
       [-2, -3,  0]])

In [8]:
numpy.hstack((A,B))

array([ 1,  2,  3, -2, -3,  0])

In [9]:
A1 = numpy.random.randint(-7,2,size=[3,4])
B1 = numpy.random.randint(-1,2,size=[3,4])
print(" avant ")
print("A = %s"%A1)
print("B = %s"%B1)
print(" après")
numpy.concatenate((A1, B1), axis=0)

 avant 
A = [[-1 -3  1  0]
 [-3 -6 -1 -3]
 [ 1 -7 -7 -2]]
B = [[ 1  0  0 -1]
 [-1 -1  1  1]
 [ 1 -1  0  0]]
 après


array([[-1, -3,  1,  0],
       [-3, -6, -1, -3],
       [ 1, -7, -7, -2],
       [ 1,  0,  0, -1],
       [-1, -1,  1,  1],
       [ 1, -1,  0,  0]])

In [10]:
A1 = numpy.random.randint(-7,2,size=[3,4])
B1 = numpy.random.randint(-1,2,size=[4,1])

print(" avant ")
print(A1)
print(B1)
print(" après")
numpy.concatenate((A1.T, B1), axis=1)

 avant 
[[-2 -7 -2  1]
 [-1 -5  1 -7]
 [-2 -5 -4 -3]]
[[ 0]
 [-1]
 [ 0]
 [ 0]]
 après


array([[-2, -1, -2,  0],
       [-7, -5, -5, -1],
       [-2,  1, -4,  0],
       [ 1, -7, -3,  0]])

In [11]:
A2 = numpy.random.randint(-3,5,size=3)
B2 = numpy.random.randint(-1,12,size=9)
print(A2)
print(B2)

numpy.r_[A2, 0, 0, B2]

[ 3 -2 -2]
[ 9 10 -1  0  1  0  0  7  8]


array([ 3, -2, -2,  0,  0,  9, 10, -1,  0,  1,  0,  0,  7,  8])